version: '3.8'

services:
  prosody:
    build: ./prosody
    container_name: prosody
    restart: unless-stopped
    ports:
      - "5222:5222"  # XMPP client connections
      - "5269:5269"  # Server-to-server connections
      - "5280:5280"  # HTTP binding / BOSH (if enabled)
    volumes:
      - ./prosody/prosody-config:/etc/prosody   # Place your custom configuration files here
      - ./prosody/prosody-data:/var/lib/prosody   # Persistent data storage
    # Optional environment variables – adjust as needed for your image
    # environment:
    #   - PROSODY_DOMAIN=example.com
    #   - PROSODY_ADMINS=admin@example.com

  agent:
    build: .
    container_name: agent
    restart: unless-stopped
    networks:
      - xmpp_network
    depends_on:
      - prosody
    environment:
      XMPP_SERVER: prosody
      XMPP_PORT: 5222
      XMPP_JID: "agent@localhost"
      XMPP_PASSWORD: "top_secret"

networks:
  xmpp_network:

volumes:
  prosody_data:
  prosody_config:
  prosody_logs: